// imports
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub, AiOutlineMail } from "react-icons/ai";
// images
import Image from "next/image";
import p2 from "../public/p2.png";
import design from "../public/design.png";
import lara from "../public/lara.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import bmi from "../public/bmi.png";
import driv from "../public/driv.png";
import bagRush from "../public/bagRush.png";
import sos from "../public/sos.png";
import yaka from "../public/yaka.png";
import mental from "../public/mental.png";
import shome from "../public/shome.png";
import vscode from "../public/vscode.png";
import recipe from "../public/recipe.png"
import movie from "../public/movie.png"
import todo from "../public/todo.png"
import ncal from "../public/ncal.png"
import piano from "../public/piano.png"
import ech from "../public/ech.png"
import events from "../public/events.png"
import student from "../public/student.jpg"
import task from "../public/task.png"
import fbclone from "../public/fbclone.png"
import hotelr from "../public/hotelr.png"
import mbook from "../public/mbook.jpg"
import news from "../public/news.jpg"
import joy from "../public/joytravel.png"
// hooks
import { useState } from "react";
import ProjectCard from "./ProjectCard";

// application
export default function Home() {
  // functions
  const [darkmode, setdarkmode] = useState(false);
  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Kavisha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="font-poppins bg-white px-5 md:px-20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-white"></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1bRPqBuA19WhOGqDHcEptZJvy9ukgNGlT?usp=sharing"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-purple-600 text-white px-4 py-2 border-none rounded-md text-sm md:text-base"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-5">
            <h2 className="text-3xl font-bold text-purple-700 md:text-4xl lg:text-7xl lg:mb-4">
              Kavisha Kahandugoda
            </h2>
            <h3 className="text-xl py-4 md:text-2xl dark:text-white">
              Mobile App & Web Developer | Frontend Developer | Full-Stack Developer | UI/UX Designer | WordPress Developer
            </h3>
            <p className="text-sm py-2 text-gray-400 leading-6 md:text-md max-w-xl mx-auto">
              An accountable and motivated 4th-year undergraduate adept at
              teamwork and tackling challenges with a positive outlook.
            </p>
          </div>

          {/* social media */}
          <div className="text-4xl flex justify-center gap-8 text-gray-600 md:text-5xl md:gap-16">
            <a
              href="https://www.linkedin.com/in/kavisha-thejan-306292376/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/Kavishathejan"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://mail.google.com/mail/?view=cm&fs=1&to=kavishatd@gmail.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiOutlineMail />
            </a>
          </div>

          {/* profile image */}
          <div className="mx-auto relative bg-gradient-to-b from-purple-200 w-64 h-64 p-5 mt-20 rounded-full md:w-80 md:h-80">
            <Image src={p2} alt="profile" layout="fill" objectFit="cover" className="rounded-full" />
          </div>
        </section>

        {/* section 2 */}
        <section>
          <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className="inline py-5"
              />
              <h3 className="text-xl font-bold dark:text-white md:text-2xl">
                UI/UX designing
              </h3>
              <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                Design tools
              </h4>
              <p className="text-gray-400 text-xs md:text-sm">Figma</p>
              <p className="text-gray-400 text-xs md:text-sm">Photoshop</p>
              <p className="text-gray-400 text-xs md:text-sm">Adobe Lightroom</p>
            </div>

            {/* Mobile app development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <Image
                src={code}
                width={100}
                height={100}
                alt="mobile app"
                className="inline py-5"
              />
              <h3 className="text-xl font-bold dark:text-white md:text-2xl">
                Mobile application & web development
              </h3>
              <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                Developing languages
              </h4>
              <p className="text-gray-400 text-xs md:text-sm">Flutter(dart)</p>
              <p className="text-gray-400 text-xs md:text-sm">React Native</p>
              <p className="text-gray-400 text-xs md:text-sm">Wordpress</p>
              <p className="text-gray-400 text-xs md:text-sm">React.js / Next.js</p>
              <p className="text-gray-400 text-xs md:text-sm">Tailwind CSS</p>
            </div>

            {/* Web development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <Image
                src={lara}
                width={100}
                height={100}
                alt="web app"
                className="inline py-5"
              />
              <h3 className="text-xl font-bold dark:text-white md:text-2xl">
                Full-stack development
              </h3>
              <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                Developing languages, Frameworks & Databases
              </h4>
              <p className="text-gray-400 text-xs md:text-sm">python/Java/C++</p>
              <p className="text-gray-400 text-xs md:text-sm">Laravel</p>
              <p className="text-gray-400 text-xs md:text-sm">HTML/CSS</p>
              <p className="text-gray-400 text-xs md:text-sm">Javascript/Bootstrap</p>
              <p className="text-gray-400 text-xs md:text-sm">Node.js / Express.js</p>
              <p className="text-gray-400 text-xs md:text-sm">MongoDB / MySQL</p>
              <p className="text-gray-400 text-xs md:text-sm">Firebase</p>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <Image
                src={vscode}
                width={100}
                height={100}
                alt="web app"
                className="inline py-5"
              />
              <h3 className="text-xl font-bold dark:text-white md:text-2xl">
                Tools/Platforms
              </h3>
              <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                IDEs and tools
              </h4>
              <p className="text-gray-400 text-xs md:text-sm">Git / GitHub</p>
              <p className="text-gray-400 text-xs md:text-sm">VS Code / IntelliJ</p>
              <p className="text-gray-400 text-xs md:text-sm">Postman</p>
            </div>
          </div>
        </section>

        {/* Project portfolio */}
        <section>
          <div>
            <h3 className="text-2xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100 md:text-3xl">
              Projects portfolio
            </h3>
          </div>

          {/* images */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Project 1 */}
            <ProjectCard
              title="Final Year Research & Project: AI Based Mobile Application For Mood Disorders Associated With Depression"
              tech="Flutter(Dart), Firebase, Node.js"
              img={web1}
              alt="Final Year Research"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/AI-Based-Mobile-Application-and-system-For-Mood-Disorders-Associated-With-Depression.git" },
                { label: "View Video", url: "https://lnkd.in/p/gGSa2f75" }
              ]}
            />

            {/* Project 2 */}
            <ProjectCard
              title="Movie Tickets Booking app"
              tech="Flutter(Dart), Firebase"
              img={mbook}
              alt="Movie Tickets App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Flutter-Firebase-Mobile-Application-for-Booking-Movie-Tickets" },
                { label: "View Video", url: "https://lnkd.in/p/g7fGh835" }
              ]}
            />

            {/* Project 3 */}
            <ProjectCard
              title="NEWS App For SRI LANKA"
              tech="Flutter(Dart), Firebase, Rest API"
              img={news}
              alt="News App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Flutter---Sri-Lanka-News-App-" },
                { label: "View Video", url: "https://lnkd.in/p/gFd3aduY" }
              ]}
            />

            <ProjectCard
              title="JoyTravel website"
              tech="React(vite), Laravel, TailwindCSS, MySQL, Phpmyadmin"
              img={joy}
              alt="Travel website"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/JoyTravel-website-React-vite-Laravel" },
                { label: "View Vercel Link", url: "https://joy-travel-frontend-react-vite.vercel.app/" }
              ]}
            />

            {/* Project 4 */}
            <ProjectCard
              title="Hotel Rooms Management System With Laravel"
              tech="Laravel, HTML, CSS, Bootstrap"
              img={hotelr}
              alt="Hotel Management"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Hotel-Rooms-Management-System-With-Laravel-" },
                { label: "View Post", url: "https://lnkd.in/p/g9HpAPGM" }
              ]}
            />

            {/* Project 5 */}
            <ProjectCard
              title="Traditional Food Recipes app with Flutter and MongoDB Compass"
              tech="Flutter(Dart), HTML, JavaScript, MongoDB Compass, Node.js"
              img={recipe}
              alt="Recipes App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Traditional-Recipes-App.git" }
              ]}
            />

            {/* Project 6 */}
            <ProjectCard
              title="Task Management App (Laravel & MySQL)"
              tech="Laravel, HTML, CSS, Bootstrap"
              img={task}
              alt="Task Management App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/TaskApp-with-Authentication--Laravel-MySQL" }
              ]}
            />

            {/* Project 7 */}
            <ProjectCard
              title="FaceBook App Clone UI with React.js"
              tech="React.js"
              img={fbclone}
              alt="Facebook Clone UI"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Facebook-Clone-App-UI-React-Tutorial-" }
              ]}
            />

            {/* Project 8 */}
            <ProjectCard
              title="Movie searching App with TMDB API"
              tech="Dart, C++, JavaScript, HTML"
              img={movie}
              alt="Movie Searching App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Movie_Searching_app_Flutter.git" }
              ]}
            />

            {/* Project 9 */}
            <ProjectCard
              title=".NET project - Student Management System"
              tech="ASP.NET, HTML, CSS, JavaScript"
              img={student}
              alt="Student Management System"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Student-Management-System---ASP.NET.git" }
              ]}
            />

            {/* Project 10 */}
            <ProjectCard
              title=".NET - Windows Forms Calculator"
              tech=".NET, C#"
              img={ncal}
              alt="Windows Forms Calculator"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Windows-Forms-Calculator_.NET.git" }
              ]}
            />

            {/* Project 11 */}
            <ProjectCard
              title="Digital Piano App"
              tech="HTML, CSS, JavaScript"
              img={piano}
              alt="Digital Piano App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/digital-piano-app.git" }
              ]}
            />

            {/* Project 12 */}
            <ProjectCard
              title="Movie-Explorer - React.js"
              tech="HTML, CSS, JavaScript"
              img={sos}
              alt="Movie Explorer"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Movie-Explorer_React.git" }
              ]}
            />

            {/* Project 13 */}
            <ProjectCard
              title="Vision based driver assist system"
              tech="HTML, Tex, Python"
              img={driv}
              alt="Driver Assist System"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/Vision_based_driver_assist_system.git" }
              ]}
            />

            {/* Project 14 */}
            <ProjectCard
              title="ToDo App - Angular, Firebase"
              tech="Angular (Framework), TypeScript, HTML, CSS"
              img={todo}
              alt="ToDo App"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/ToDo-App---Angular-Firebase.git" }
              ]}
            />

            {/* Project 15 */}
            <ProjectCard
              title="BMI Calculator"
              tech="Dart, C++, JavaScript, HTML"
              img={bmi}
              alt="BMI Calculator"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/finalpro.git" }
              ]}
            />

            {/* Project 16 */}
            <ProjectCard
              title="Bag Rush Adventure Game"
              tech="Unity, VS Code"
              img={web3}
              alt="Bag Rush Adventure Game"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://www.linkedin.com/posts/nisal-basura-wickramasinghe-06884820b_techchallenge02-unity-gamedevelopment-ugcPost-7210110628202516480-Vgns?utm_source=share&utm_medium=member_desktop" }
              ]}
            />

            {/* Project 17 */}
            <ProjectCard
              title="E-Channeling Website"
              tech="HTML, CSS, JavaScript, PHP"
              img={ech}
              alt="E-Channeling Website"
              hoverLinks={[
                { label: "View GitHub Repo", url: "https://github.com/Kavishathejan/E-Channeling-web.git" }
              ]}
            />

          </div>

        </section>

        {/* Figma UI designs portfolio */}
        <section>
          <div>
            <h3 className="text-2xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100 md:text-3xl">
              Figma UI designs portfolio
            </h3>
          </div>

          <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <a
                href="https://www.figma.com/design/GRrgOyziOsseHtNKyxlVYX/event-booking-and-management-app?node-id=9-1886&t=bB39j1SEqch1ksVc-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="w-50 h-80 relative mx-auto">
                  <Image
                    src={events}

                    alt="Events Management web app"
                    className="rounded-lg object-cover"
                    layout="fill"
                  />
                </div>
                <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                  Figma
                </h4>
                <h4 className="py-2 text-black-600 text-sm font-semibold dark:text-white md:text-md">
                  User interace designs for Events Management web app
                </h4>
              </a>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <a
                href="https://www.figma.com/design/mMTnSLmI3l3q8PXhBcJtlq/Untitled?node-id=0-1&t=9mN4wt3XgRzW8zya-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="w-25 h-80 relative mx-auto">
                  <Image
                    src={yaka}
                    alt="traditional masks selling app"
                    className="rounded-lg object-cover"
                    layout="fill"
                  />
                </div>
                <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                  Figma
                </h4>
                <h4 className="py-2 text-black-600 text-sm font-semibold dark:text-white md:text-md">
                  User interace designs for traditional masks selling app (mobile)
                </h4>
              </a>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <a
                href="https://www.figma.com/design/7pdceie8mwvaCmm5CvMnEq/FYP?node-id=0-1&t=EGXLERxrr32G9Mt7-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="w-25 h-80 relative mx-auto">
                  <Image
                    src={mental}
                    alt="mental health app"
                    className="rounded-lg object-cover"
                    layout="fill"
                  />
                </div>
                <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                  Figma
                </h4>
                <h4 className="py-2 text-black-600 text-sm font-semibold dark:text-white md:text-md">
                  User interace designs for mental health app (mobile)
                </h4>
              </a>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-5 dark:bg-gradient-to-b from-gray-800">
              <a
                href="https://www.figma.com/design/jPOvyBtj3ziwRkU7xi7kBf/Smart-Home?node-id=0-1&t=eF4JA01YkBKv78Sd-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="w-25 h-80 relative mx-auto">
                  <Image
                    src={shome}
                    alt="SmartHome"
                    className="rounded-lg object-cover"
                    layout="fill"
                  />
                </div>
                <h4 className="py-4 text-purple-600 text-sm font-semibold md:text-md">
                  Figma
                </h4>
                <h4 className="py-2 text-black-600 text-sm font-semibold dark:text-white md:text-md">
                  User interace designs for SmartHome (desktop/mobile/tablet)
                </h4>
              </a>
            </div>
          </div>
        </section>

        <footer className="py-10 text-center">
          <h4 className="text-black-600 text-sm font-medium dark:text-white md:text-md">
            © 2024 Kavisha Thejan Kahandugoda
            <br />
            All Rights Reserved
          </h4>
        </footer>
      </main>
    </div>
  );
}