// imports
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub,AiOutlineMail } from "react-icons/ai";
// images
import Image from "next/image";
import p2 from "../public/p2.png";
import design from "../public/design.png";
import lara from "../public/lara.png";
import code from "../public/code.png";
import web1 from "../public/web1.svg";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import bmi from "../public/bmi.png";
import driv from "../public/driv.png";
import bagRush from "../public/bagRush.png";
import sos from "../public/sos.png";
import yaka from "../public/yaka.png";
import mental from "../public/mental.png"; 
import shome from "../public/shome.png";// Add the image for Bag Rush game
// hooks
import { useState } from "react";

// application
export default function Home() {
  // functions
  const [darkmode, setdarkmode] = useState(false);
  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Kavisha's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins bg-white px-10 md:px-20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          <nav className="py-10 mb12 flex justify-between">
            <h1 className=" text-xl dark:text-white"></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1q3jPHd8ZfnLtYUD66JWnlDefhIvYTspp/view?usp=drive_link" target="_blank"  rel="noopener noreferrer"
                  className=" bg-purple-600 text-white px-4 py-2 border-none rounded-md "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-5 ">
            <h2 className=" text-5xl font-bold text-purple-700 md:text-4xl lg:text-7xl lg:mb-4">
              Kavisha Kahandugoda
            </h2>
            <h3 className="text-2xl py-4 md:text-xl dark:text-white">
              UI/UX designer and Full-stack developer
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6 md:text-md max-w-xl mx-auto">
              An accountable and motivated 4th-year undergraduate, adept at
              teamwork and tackling challenges with a positive outlook.
            </p>
          </div>
          {/* social media */}
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a
              href="https://www.linkedin.com/in/kavisha-thejan-8b0825305?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
              target="_blank"  rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Kavishathejan" target="_blank"  rel="noopener noreferrer">
              <AiFillGithub />
            </a>
            <a href="mailto:kavishadulanjanastc@gmail.com" target="_blank" rel="noopener noreferrer"  >
  <AiOutlineMail />
</a>

          </div>
          {/* profile image */}
          <div
            className=" m-auto relative bg-gradient-to-b from-purple-200 w-80 p-5 h-80 mt-20 rounded-full o"
          >
            <Image src={p2} alt="profile" layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* section 2 */}
        <section>
          <div></div>
          <div className="md:flex lg:flex gap-10 mx-auto">
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white ">
                UI/UX designing
              </h3>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Design tools
              </h4>
              <p className=" text-gray-400 text-sm">Photoshop</p>
              <p className=" text-gray-400 text-sm">Figma</p>
            </div>

            {/* Mobile app development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <Image
                src={code}
                width={100}
                height={100}
                alt="mobile app"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white">
                Mobile application development
              </h3>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Developing languages
              </h4>
              <p className=" text-gray-400 text-sm">Flutter</p>
            </div>

            {/* Web development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <Image
                src={lara}
                width={100}
                height={100}
                alt="web app"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white">
                Full-stack development
              </h3>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Developing languages
              </h4>
              <p className=" text-gray-400 text-sm">Laravel</p>
              <p className=" text-gray-400 text-sm">HTML/CSS</p>
              <p className=" text-gray-400 text-sm">python/Java/C++</p>
              <p className=" text-gray-400 text-sm">Javascript/Bootstrap</p>
            </div>
          </div>
        </section>

                {/* Project portfolio */}
                <section>
          <div>
            <h3 className=" text-3xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100">
              Projects portfolio
            </h3>
          </div>

          {/* images */}
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <h3 className=" text-1xl py-5 font-semibold opacity-100 dark:text-white dark:opacity-100">
                E-Channeling-web
              </h3>
              <a href="https://github.com/Kavishathejan/E-Channeling-web.git" target="_blank"  rel="noopener noreferrer">
                <div className="w-72 h-72 mx-auto"> {/* Uniform width and height */}
                  <Image
                    src={web1}
                    alt="web images"
                    className="rounded-lg object-cover"
                    layout="responsive"
                    width={400}   
                    height={400}  
                  />
                </div>
              </a>

              <h3 className=" text-1xl py-5 font-semibold opacity-100 dark:text-white dark:opacity-100">
                BMI calculator
              </h3>
              <a href="https://github.com/Kavishathejan/finalpro.git" target="_blank"  rel="noopener noreferrer">
                <div className="w-72 h-72 mx-auto"> {/* Uniform width and height */}
                  <Image
                    src={bmi}
                    alt="BMI calculator"
                    className="rounded-lg object-cover"
                    layout="responsive"
                    width={400}   
                    height={400}  
                  />
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className=" text-1xl py-5 font-semibold opacity-100 dark:text-white dark:opacity-100">
                Vision based driver assist system
              </h3>
              <a href="https://github.com/Kavishathejan/Vision_based_driver_assist_system.git" target="_blank" rel="noopener noreferrer">
                <div className="w-72 h-72 mx-auto"> {/* Uniform width and height */}
                  <Image
                    src={driv}
                    alt="Driver assist system"
                    className="rounded-lg object-cover"
                    layout="responsive"
                    width={400}   
                    height={400}  
                  />
                </div>
              </a>

              <h3 className=" text-1xl py-5 font-semibold opacity-100 dark:text-white dark:opacity-100">
                Bag Rush Adventure Game
              </h3>
              <a href="https://www.linkedin.com/posts/nisal-basura-wickramasinghe-06884820b_techchallenge02-unity-gamedevelopment-ugcPost-7210110628202516480-Vgns?utm_source=share&utm_medium=member_desktop" target="_blank"  rel="noopener noreferrer">
                <div className="w-72 h-72 mx-auto"> {/* Uniform width and height */}
                  <Image
                    src={web3}
                    alt="Bag Rush Adventure Game"
                    className="rounded-lg object-cover"
                    layout="responsive"
                    width={400}   
                    height={400}  
                  />
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className=" text-1xl py-5 font-semibold opacity-100 dark:text-white dark:opacity-100 text-center" >
                Laravel SOS App
              </h3>
              <a href="https://github.com/Kavishathejan/alarms.git" target="_blank" rel="noopener noreferrer">
                <div className="w-72 h-72 mx-auto"> {/* Uniform width and height */}
                  <Image
                    src={sos}
                    alt="Laravel SOS App"
                    className="rounded-lg object-cover"
                    layout="responsive"
                    width={40}   
                    height={40}  
                  />
                </div>
              </a>
            </div>
          </div>
        </section>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

        {/* Figma UI designs portfolio */}
        <section>
          <div>
            <h3 className=" text-3xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100">
              Figma UI designs portfolio
            </h3>
          </div>
          <div className="md:flex lg:flex gap-10 mx-auto">
          <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <a href="https://www.figma.com/design/mMTnSLmI3l3q8PXhBcJtlq/Untitled?node-id=0-1&t=9mN4wt3XgRzW8zya-1"><Image
                src={yaka}
                width={300}
                height={300}
                alt="web app"
                className=" inline py-5"
              />
              
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Figma
              </h4>
              <h4 className="py-4 text-black-600 text-md font-semibold dark:text-white">
                
                User interace designs for <br />traditional masks selling app <br /> (mobile)
              </h4>
              </a>
            </div>

            {/* Mobile app development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <a href="https://www.figma.com/design/jiKUeJzcnRf1ox2xEwu38b/FYP?node-id=0-1&t=vGx2O2LSenEcrFrD-1" target="_blank"  rel="noopener noreferrer"><Image
                src={mental}
                width={300}
                height={300}
                alt="mobile app"
                className=" inline py-5"
              />
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Figma
              </h4>
              
              <h4 className="py-4 text-black-600 text-md font-semibold dark:text-white">
                
                User interace designs for <br />mental health app (mobile)
              </h4>
              </a>
            </div>

            {/* Web development */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <a href="https://www.figma.com/design/IchfP3O9QoxZtqzbGutO7G/Untitled?node-id=0-1&t=36XUF0dfM4bPWG7L-1"><Image
                src={shome}
                width={300}
                height={300}
                alt="web app"
                className=" inline py-5"
              />
              
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Figma
              
              </h4>
              <h4 className="py-4 text-black-600 text-md font-semibold dark:text-white">
                
                User interace designs for <br />SmartHome (desktop,mobile,tablet)
              </h4>
              </a>
            </div>
          </div>

          
        </section>
        <section>
        <h4 className="py-4 text-black-600 text-md font- text-center dark:text-white">
        © 2024 Kavisha Thejan Kahandugoda 
        All Rights Reserved
              
              </h4>
              
        </section>

      </main>
    </div>
  );
}
